version: '3.9'  
  
services:  
  api:  
    build:  
      context: ./
      dockerfile: ./API/Dockerfile  
    container_name: api_container
    env_file: .env
    ports:
        - 8081:80
    depends_on:
        - sqlite

  sqlite:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - C:\\SQLite\EffectiveCats.sqlite:/var/lib/sqlite/data

volumes:
  sqlite:
    driver: local